name: 'Dismiss reviews if stale'
description: >
  An action which will dismiss reviews if they are stale. Notably, this action behaves
  correctly even if the branch was rebased or force pushed (versus GitHub's built-in
  dismiss if stale functionality).
author: 'Krishna Vudata'
inputs:
  mode:
    required: true
    description: 'Specify either "check-for-approvals" or "dismiss-stale-reviews"'
  path_to_cached_diff:
    description: >
      Path to the cached diff file. Only required for dismiss-stale-reviews mode.
  path_to_cached_metadata:
    description: >
      Path to the cached approval metadata JSON file. Used for range-diff comparison
      which is more accurate for rebased branches. If not provided or file doesn't
      exist, falls back to diff comparison. Only relevant in dismiss-stale-reviews mode.
  token:
    description: >
      GitHub token - at a minimum, this must have
      'contents: read' and 'pull-requests: write' permissions.
    default: '${{ github.token }}'
  diffs_directory:
    description: >
      Optional directory to store diffs - useful for debugging what changes led to
      approval dismissals. Only relevant in dismiss-stale-reviews mode.
  repo_path:
    description: >
      Path to the repo for the pull request - if the repo is not already checked out to
      this path, then it will be. There are some cases where we need to compute the diff
      using git and the repo directly.
      Only relevant in dismiss-stale-reviews mode.
    default: '${{ github.workspace }}'
outputs:
  approved_sha:
    description: >
      The SHA of the commit that was approved. Only set in check-for-approvals mode, and
      if there is an approval on the PR. Otherwise, this will be an empty string.
  review_id:
    description: >
      The ID of the approval review. Used for cache key lookup. Only set (non-empty)
      in check-for-approvals mode when there is an approval on the PR. Empty string
      if there are no approvals or in dismiss-stale-reviews mode.
runs:
  using: 'node16'
  main: 'dist/index.js'
