name: 'Dismiss reviews if stale'
description: >
  An action which will dismiss reviews if they are stale. Notably, this action behaves
  correctly even if the branch was rebased or force pushed (versus GitHub's built-in
  dismiss if stale functionality).
author: 'Krishna Vudata'
inputs:
  mode:
    required: true
    description: 'Specify either "check-for-approvals" or "dismiss-stale-reviews"'
  path_to_cached_diff:
    description: >
      Path to the cached diff file. Only required for dismiss-stale-reviews mode.
  token:
    description: 'GitHub token'
    default: '${{ github.token }}'
outputs:
  approved_sha:
    description: >
      The SHA of the commit that was approved. Only set in check-for-approvals mode, and
      if there is an approval on the PR. Otherwise, this will be an empty string.
runs:
  using: 'node16'
  main: 'dist/index.js'
